#!/usr/bin/env python
import tornado.ioloop
import tornado.web
from huskyhunter.base import application

if __name__ == "__main__":
    application.listen(8888)
    tornado.ioloop.IOLoop.instance().start()
